###
# Configuration file for roommodes program.
###

###
# Temperature and RH. Units are degrees celcius
# and fractional saturation: 0 < RH < 1.
###
temp = 23
rh = 0.6

###
# Room dimensions in meters.
###
length = 8.4
width = 6.1
height = 2.5

###
#
#  y dimension
#  |
#  |
#  +-----------------------------------------+
#  |                                         |
#  |                                         |
#  |  R                                      |
#  |                                         |
#  |                     =+                  |
#  |                    | |                  |
#  |                     =+                  |
#  |                    | |                  |
#  |                     =+                  |
#  |                                         |
#  |  L                                      |
#  |                                         |
#  |                                         |
#  +-----------------------------------------+--> x dimension
#   \
#    +- (0, 0)
###

###
# Initial location of the L speaker relative to the
# origin in the drawing in meters.
###

xpos = 0.75
ypos = 1.3
zpos = 0.67


###
# Simulation parameters
###
n = 4 # number of harmonics to consider.
cellsize = 0.1

